name: Main Workflow

on:
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-20.04

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4

              with:
                python-version: 3.10

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8==7.1.1 flake8-isort==6.1.1

            - name: Test with flake8

              run: python -m flake8 bookmarks/